---
- name: Copy Qualys agent RPM
  copy:
    src: qualys-cloud-agent.rpm
    dest: /tmp/qualys-cloud-agent.rpm
  tags: qualys

- name: Install/Update Qualys agent
  yum:
    name: /tmp/qualys-cloud-agent.rpm
    state: latest
  become: yes # as root
  tags: qualys

- name: Activate agent
  command:
    argv:
      - /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh
      - 'ActivationId={{ qualys_activation_id }}'
      - 'CustomerId={{ qualys_customer_id }}'
  become: yes # as root
  tags: qualys

- name: Cleanup Qualys agent RPM
  file:
    path: /tmp/qualys-cloud-agent.rpm
    state: absent
  tags: qualys