---
- name: Ensure nginx certs directory exists
  file:
    path: '{{ proxy_container_path }}/certs'
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'
  become: yes
  tags: certs

- name: Copy nginx certificate
  copy:
    src: '{{ role_name }}/{{ ssl_cert_domain }}.crt'
    dest: '{{ proxy_container_path }}/certs/'
    mode: '0644'
  become: yes
  tags: certs

# Funky way of including an OPTIONAL file and registering it for later use
# If the file isn't copied then the sites will NOT have OCSP Stapling
- name: Copy (optional) nginx certificate chains
  copy:
    src: '{{ item }}'
    dest: '{{ proxy_container_path }}/certs/'
    mode: '0644'
  become: yes
  with_first_found:
    - files:
        - '{{ role_name }}/{{ ssl_cert_domain }}.chain.crt'
      skip: yes
  register: ssl_ocsp_stapling
  tags: certs

- name: Copy nginx certificate keys
  copy:
    src: '{{ role_name }}/{{ ssl_cert_domain }}.key'
    dest: '{{ proxy_container_path }}/certs/'
    mode: '0600'
  become: yes
  tags: certs

- name: Generate Diffie-Hellman parameters (only for intermediate/old sites)
  openssl_dhparam:
    path: '{{ proxy_container_path }}/certs/dhparam.pem'
    size: '{{ dhparam_size }}'
  become: yes
  when: ssl_config_type != "modern"
  tags:
    - certs
    - dhparam
    