---
- import_tasks: certs.yml
  tags:
    - proxy
    - certs

- import_tasks: sites.yml
  tags:
    - proxy
    - sites

- name: Create/Update nginx configuration
  copy:
    src: nginx.conf
    dest: '{{ proxy_container_path }}/nginx.conf'
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: proxy

- name: Create/Update nginx proxy_params
  copy:
    src: proxy_params
    dest: '{{ proxy_container_path }}/proxy_params'
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: proxy

- name: Create/Update nginx-proxy docker container
  docker_container:
    name: nginx-proxy
    image: nginx:alpine
    pull: true
    network_mode: host
    ulimits: nofile:8192:8192
    restart_policy: unless-stopped
    volumes:
      - '{{ proxy_container_path }}/nginx.conf:/etc/nginx/nginx.conf'
      - '{{ proxy_container_path }}/proxy_params:/etc/nginx/proxy_params'
      - '{{ proxy_container_path }}/sites:/etc/nginx/sites-enabled'
      - '{{ proxy_container_path }}/certs:/etc/ssl/private'
    comparisons:
      '*': strict
  become: yes
  tags: proxy
