---
- name: Ensure nginx sites directory exists
  file:
    path: '{{ proxy_container_path }}/sites'
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'
  become: yes
  tags: sites

- name: Create nginx site configuration
  template:
    src: '{{ ssl_config_type }}.conf.j2'
    dest: '{{ proxy_container_path }}/sites/application.conf'
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: sites
      
    