---
- import_tasks: repo.yml
  tags:
    - cortex
    - repo

- name: Install/Update Extra Packages for Enterprise Linux
  yum:
    name: epel-release
    state: latest
  tags: cortex

- name: Install/Update globally required dependencies
  yum:
    name:
      - git
      - python-devel
      - python-pip
      - python3-devel
      - python3-pip
      - '@Development Tools'
    state: latest
  become: yes
  tags:
    - cortex
    - python

- name: Install/Update Cortex
  yum:
    name: cortex
    state: latest
  tags: cortex

- name: Create/Update Cortex configuration
  template:
    src: application.conf.j2
    dest: /etc/cortex/application.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  register: cortex_config
  tags: cortex

- import_tasks: analyzers.yml
  tags: cortex

- name: Restart Cortex service to load new configuration changes 
  systemd:
    name: cortex
    state: restarted
    daemon_reload: yes
  become: yes
  when: cortex_config.changed
  tags: cortex

- name: Ensure Cortex service is enabled and running 
  systemd:
    name: cortex
    enabled: yes
    state: started
  become: yes
  tags: cortex
