---
# Generate APP_KEY with: echo "base64:$(openssl rand -base64 32)"
bookstack_app_key: ''

# BookStack URL
# Required for 3rd-party logins
bookstack_app_url: https://docs.example.com

# User and Group settings
bookstack_uid: 1000
bookstack_gid: 1000

# Database settings
bookstack_db_host: localhost
bookstack_db_name: bookstack
bookstack_db_user: bookstack
bookstack_db_password: bookstack

# BookStack version to pull
bookstack_container_version: latest

# Container network settings
bookstack_http_port: 80
bookstack_https_port: 443
bookstack_container_host: 0.0.0.0

# BookStack volumes for persistent storage
bookstack_container_volume: /srv/docker/bookstack

# SSL configuration type
# See: https://ssl-config.mozilla.org/
ssl_config_type: modern

# Certificate domain
ssl_cert_domain: '{{ bookstack_app_url | regex_replace("^https?://", "") }}'

# HSTS settings
ssl_hsts_enabled: no
ssl_hsts_age: 63072000

# OCSP Stapling settings
ssl_ocsp_stapling_resolvers:
  - 1.1.1.1
  - 1.0.0.1

# Diffie-Hellman key size
dhparam_size: 4096