---
# Generate APP_KEY with: echo "base64:$(openssl rand -base64 32)"
bookstack_app_key: ''
bookstack_app_url: https://docs.example.com

# Database options
bookstack_db_host: localhost:3306
bookstack_db_name: bookstack
bookstack_db_user: bookstack
bookstack_db_password: bookstack

# Container options
bookstack_container_version: latest
bookstack_container_port: 8080
bookstack_container_host: 127.0.0.1
bookstack_container_uploads_path: /srv/docker/bookstack/uploads
bookstack_container_storage_path: /srv/docker/bookstack/storage
bookstack_container_timezone: America/New_York