---
# Elasticsearch settings
elasticsearch_index_name: cortex
elasticsearch_uris: []
#  - http://127.0.0.1:9200/

# Cortex secret key for secured communications
# This MUST be the same across multiple instances
cortex_secret_key: '***CHANGE_ME***'

# Cortex port
cortex_port: 9001

# Analyzers and Responders
# Repos will be automatically pulled into /opt
cortex_analyzers:
  - repo: https://github.com/TheHive-Project/Cortex-Analyzers

    # Directory within the repo that holds Analyzers/Responders
    # Use '.' to use the entire repo as an Analyzer/Responder
    # Leave blank/unset if the repo doesn't have any Analyzers/Responders
    analyzers_dir: analyzers
    responders_dir: responders

    # Additional system packages needed by Analyzers/Responders
    system_pkgs:
      - python-wheel
      - python3-wheel
      - libffi-devel
      - ssdeep-devel
      - ssdeep-libs
      - perl-Image-ExifTool
      - perl-File-LibMagic
      - openssl-devel
