---
- name: Add SSH keys to authorized_keys
  authorized_key:
    user: '{{ ssh_user }}'
    key: '{{ item }}'
    state: present
  with_items: '{{ ssh_pubkeys }}'
  tags: [common, ssh]

- name: Attempt to fix RPM database errors
  command:
    cmd: rpm --rebuilddb
    warn: no
  tags: common

- import_tasks: mounts.yml
  when: additional_mounts | length
  tags: common

- import_tasks: updates.yml
  tags: common

- import_tasks: extras.yml
  tags: common

- name: Perform full system update
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: yum_updates
  tags: [common, update]

- name: Set system hostname
  hostname:
    name: '{{ inventory_hostname }}'
  register: hostname
  tags: common

- import_tasks: qualys.yml
  when: qualys_activation_id != "" and qualys_customer_id != ""
  tags: common

- name: Reboot system to fully apply all changes
  reboot:
    reboot_timeout: 3600
  when: yum_updates.changed or hostname.changed
  tags: common
