---
- name: Set system hostname
  hostname:
    name: '{{ inventory_hostname }}'
  become: yes
  tags: common

- name: Attempt to fix RPM database errors
  command:
    cmd: rpm --rebuilddb
    warn: no
  become: yes
  tags: common

- name: Add SSH keys to authorized_keys
  authorized_key:
    user: '{{ ansible_user }}'
    key: '{{ item.key }}'
    state: '{{ item.state }}'
  with_items: '{{ ssh_pubkeys }}'
  tags:
    - common
    - ssh

- import_tasks: mounts.yml
  tags:
    - common
    - mounts

- import_tasks: yumcron.yml
  tags: 
    - common
    - yumcron

- name: Install deltarpm for optimized updates
  yum:
    name: deltarpm
    state: latest
  become: yes
  tags: common

- name: Install Python for future Ansible modules
  yum:
    name:
      - python
      - python3
      - python-pip
      - python3-pip
    state: latest
  become: yes
  tags: python

- name: Perform full system update
  yum:
    name: '*'
    state: latest
    update_cache: yes
  become: yes
  register: yum_update
  tags:
    - common
    - updates

- name: Reboot system to fully apply all changes
  reboot:
    reboot_timeout: 3600
  become: yes
  when: yum_update.changed
  tags: common
