---
- include_task: '{{ ansible_os_family | lower }}.yml'
  when: ansible_distribution != "Amazon"
  tags: docker

# Amazon is bit unique...
# Only works on Amazon Linux 2
- include_tasks: amazon.yml
  when: ansible_distribution == "Amazon"
  tags: docker

- name: Enable docker service and ensure it is running
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes # as root
  tags: docker

# This is required for any Ansible docker modules
- name: Install docker Python package
  pip:
    name: docker
    state: latest
    umask: '0022' # Allow all users to access this
  become: yes # as root
  tags: docker