---
- import_tasks: repo.yml
  tags:
    - docker
    - repo

- name: Install/Update docker
  yum:
    name: docker
    state: latest
  become: yes
  tags: docker

- name: Ensure docker service is enabled and running 
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
  tags: docker

- name: Install/Update required Python packages for docker
  yum:
    name:
      - python
      - python3
      - python-pip
      - python3-pip
    state: latest
  become: yes
  tags:
    - docker
    - python

- name: Install/Update docker pip package for Ansible modules
  pip:
    name: docker
    state: latest
    umask: '0022'   # accessible globally
  become: yes
  tags:
    - docker
    - python
